Changes to run typeobject tests
eProsima/IDL-Parser pull request #103
Opened 2023-11-07 15:02 UTC by adriancampo

2023-11-07 15:26 UTC, JLBuenoLopez-eProsima requested changes

2023-11-07 15:26 UTC, JLBuenoLopez-eProsima commented on src/it/java/com/eprosima/integration/Test.java
> +        String flags = " -cdr " + cdr_version + " -replace -example" + " " + exampleArch + (testFlag ? " -test" : "") + (testType == TestType.TYPEOBJECTS ? " -typeobject" : "");
This branch have been rebased against `master` and it should not have. Here there are changes related to

* eProsima/Fast-DDS-Gen#256

which has not been merged. Also, this PR should go to an intermediate branch and not against master so I can apply changes with the implementation. Please, rebase this branch removing the latest master commit and create the intermediate branch.

2023-11-07 15:26 UTC, JLBuenoLopez-eProsima commented on src/it/java/com/eprosima/integration/Test.java
> +        return exitStatus;
```suggestion
        return Command.execute("ctest -V" + " ./" + executableName, outputPath + "/build", errorOutputOnly, false);
```

2023-11-07 15:26 UTC, JLBuenoLopez-eProsima commented on src/it/java/com/eprosima/integration/TestManager.java
> +        this.typeobjectFlag = typeobjectFlag;
Taking the latest master commit, this function has been duplicated. Please, fix this removing that commit (2d87dae0de77f789220fdcc9b0455ad62d4f02af).

2023-11-08 08:05 UTC, adriancampo commented on src/it/java/com/eprosima/integration/Test.java
> +        String flags = " -cdr " + cdr_version + " -replace -example" + " " + exampleArch + (testFlag ? " -test" : "") + (testType == TestType.TYPEOBJECTS ? " -typeobject" : "");
Fixed by rebasing again and created intermediate branch.

2023-11-08 08:05 UTC, adriancampo commented on src/it/java/com/eprosima/integration/TestManager.java
> +        this.typeobjectFlag = typeobjectFlag;
Fixed by rebasing again and created intermediate branch.

2023-11-08 08:10 UTC, adriancampo commented on src/it/java/com/eprosima/integration/Test.java
> +        return exitStatus;
When 'execute' returns null, this helps make the output a little bit prettier

2023-11-13 09:31 UTC, JLBuenoLopez-eProsima commented on src/it/java/com/eprosima/integration/Test.java
> +        return exitStatus;
I disagree. `execute` always returns a boolean.

2023-11-13 09:42 UTC, JLBuenoLopez-eProsima commented on src/it/java/com/eprosima/integration/TestManager.java
> +        this.typeobjectFlag = typeobjectFlag;
There is still a new TestManager constructor. I suggest using the two already defined instead of defining a new redundant one.

2023-11-24 06:40 UTC, JLBuenoLopez-eProsima commented on src/main/java/com/eprosima/idl/context/Context.java
> +        autoidann.addMember(new AnnotationMember("value", autoidannenum, "HASH"));
This is specifically the definition of the annotation. The same contained in [`BuiltinAnnotations.idl`](https://github.com/eProsima/Fast-DDS/blob/feature/type-object-builder-registry/src/cpp/fastdds/xtypes/type_representation/BuiltinAnnotations.idl). So this is exactly what the specification defines: if the builtin annotation is specified but no value is provided, the one to be used is `HASH` and not sequential.

2023-11-24 06:51 UTC, JLBuenoLopez-eProsima commented on src/main/java/com/eprosima/idl/context/Context.java
> +        try_construct_annotation.addMember(new AnnotationMember("value", try_construct_fail_action_enum, "USE_DEFAULT"));
See my answer to a previous similar suggestion. The default value if the annotation is not present is defined [here](https://github.com/eProsima/IDL-Parser/blob/feature/tests-typeobject/src/main/java/com/eprosima/idl/parser/typecode/MemberAppliedAnnotations.java#L48)

2023-11-24 07:31 UTC, adriancampo commented
Changes LGTM

2023-11-24 07:31 UTC, JLBuenoLopez-eProsima approved these changes

2023-11-24 07:32 UTC, merged