[20129] New API and fixes for TypeObject generation
eProsima/IDL-Parser pull request #119
Opened 2023-12-20 15:02 UTC by JLBuenoLopez-eProsima

2023-12-22 09:42 UTC, richiware requested changes

2023-12-22 09:42 UTC, richiware commented on src/main/java/com/eprosima/idl/parser/tree/Annotation.java
> +        return null;
maybe it's better to throw a `RuntimeGenerationException`.

2023-12-22 09:42 UTC, richiware commented on src/main/java/com/eprosima/idl/parser/tree/Annotation.java
> +        return null;
maybe it's better to throw a `RuntimeGenerationException`.

2023-12-22 09:42 UTC, richiware commented on src/main/java/com/eprosima/idl/parser/tree/Annotation.java
> +            return null;
maybe it's better to throw a `RuntimeGenerationException`.

2023-12-22 09:42 UTC, richiware commented on src/main/java/com/eprosima/idl/parser/typecode/AliasTypeCode.java
> +        return null;
maybe it's better to throw a `RuntimeGenerationException`.

2023-12-22 09:42 UTC, richiware commented on src/main/java/com/eprosima/idl/parser/typecode/EnumTypeCode.java
> +        // TODO: pending @bit_bound annotation application to enum types
Here there is a TODO

2023-12-22 09:42 UTC, richiware commented on src/main/java/com/eprosima/idl/parser/typecode/ArrayTypeCode.java
> +            if (Integer.parseInt(evaluated_dimensions_.get(count)) > 256)
```suggestion
            if (Integer.parseInt(evaluated_dimensions_.get(count)) >= 256)
```

2023-12-22 09:42 UTC, richiware commented on src/main/java/com/eprosima/idl/parser/typecode/MapTypeCode.java
> +        if (isIsBounded() && Integer.parseInt(evaluated_maxsize_) > 256)
```suggestion
        if (isIsBounded() && Integer.parseInt(evaluated_maxsize_) >= 256)
```

2023-12-22 09:42 UTC, richiware commented on src/main/java/com/eprosima/idl/parser/typecode/MemberedTypeCode.java
> +    public boolean isNonForwardedContent()
Does `StructTypeCode` have a override which checks also the member of the base_type in case there is inheritance?

2023-12-22 09:42 UTC, richiware commented on src/main/java/com/eprosima/idl/parser/typecode/SequenceTypeCode.java
> +        if (isIsBounded() && Integer.parseInt(evaluated_maxsize_) > 256)
```suggestion
        if (isIsBounded() && Integer.parseInt(evaluated_maxsize_) >= 256)
```

2023-12-22 09:42 UTC, richiware commented on src/main/java/com/eprosima/idl/parser/typecode/StringTypeCode.java
> +                if (isIsBounded() && Integer.parseInt(evaluated_maxsize_) > 256)
```suggestion
                if (isIsBounded() && Integer.parseInt(evaluated_maxsize_) >= 256)
```

2023-12-22 09:42 UTC, richiware commented on src/main/java/com/eprosima/idl/parser/typecode/StringTypeCode.java
> +                if (isIsBounded() && Integer.parseInt(evaluated_maxsize_) > 256)
```suggestion
                if (isIsBounded() && Integer.parseInt(evaluated_maxsize_) >= 256)
```

2023-12-22 09:42 UTC, richiware commented on src/main/java/com/eprosima/idl/parser/typecode/StructTypeCode.java
> +        return getMembers().get(0);
Is there no need of checking there is less one member? STG files doesn't fail with empty structures or might fail and we have to detect throwing a `RuntimeGenerationexception`?

2023-12-22 09:42 UTC, richiware commented on src/main/java/com/eprosima/idl/parser/typecode/TypeCode.java
> +        return null;
Calling this function it is not an error generationg the STG file? Maybe it is better to throw a `RuntimeGenerationException`.

2023-12-22 09:42 UTC, richiware commented on src/main/java/com/eprosima/solution/Solution.java
> +		return null;
maybe it's better to throw a `RuntimeGenerationException`.

2024-01-04 13:15 UTC, JLBuenoLopez-eProsima commented on src/main/java/com/eprosima/idl/parser/typecode/EnumTypeCode.java
> +        // TODO: pending @bit_bound annotation application to enum types
Out of scope. This PR is only introducing the API that will be implemented at some point (when `@bit_bound` builtin annotation is applied to enumerations as XTypes specification defines). Right now it always returns the default value: 32.

2024-01-08 08:05 UTC, richiware approved these changes
Pending a link where CI passes

2024-01-15 10:50 UTC, merged