XTypes v1.3 refactor
eProsima/IDL-Parser pull request #130
Opened 2024-04-04 07:51 UTC by JLBuenoLopez-eProsima

This PR includes changes required to generate the XTypes v1.3 IDL files and the code to register the associated TypeObjects defined in the specification. Specifically, this PR includes:

* New `-genapi` option that prepends to the OMG IDL module names the `eprosima::fastdds` namespace (developer option).
* Remove `-cdr` option because from this point onward only Fast CDR v2 is going to be supported.
* New `-default-container-prealloc-size` option to select how many elements to preallocate in the generated code for unbounded collections.
* New `-no-typeobject-support` option to disable the TypeObject code generation.
* Infrastructure to add tests for TypeObject generated code.
* Several refactors for typecodes:
    * Unions: discriminator and default value.
    * C++ enum class
    * New MemberAppliedAnnotations class to apply annotations to collection elements (partially supported. Collection element annotations are not yet parsed in the grammar and added to the element).
    * Correctly register builtin annotations defined in IDL v4.2 and XTypes v1.3 specifications. Add API to access and check builtin annotations.
    * Fix collections API to return correct TypeIdentifier discriminator depending on the bound size.
    * Extend primitive Typecode API to check primitive kind.
    * API to return collection's size.
* STGroup template configuration
* Improve documentation

2024-04-05 09:30 UTC, richiware requested changes

2024-04-05 09:30 UTC, richiware commented on src/main/java/com/eprosima/idl/parser/tree/Annotation.java
> +        if (getName().equals(Annotation.id_str) ||
Sort alphabetically

2024-04-05 09:30 UTC, richiware commented on src/main/java/com/eprosima/idl/parser/typecode/MemberAppliedAnnotations.java
> +    public boolean isAnnotationOptional()
[optional] sort alphabetically and several funcion of same annotation group using `//{{{ @autoid`

2024-04-05 09:30 UTC, richiware commented on src/main/java/com/eprosima/idl/parser/typecode/MemberedTypeCode.java
>          if (member.isAnnotationOptional() && Kind.KIND_STRUCT != getKind())
sort alphabetically by annotation name

2024-04-08 05:15 UTC, richiware commented on src/main/java/com/eprosima/idl/parser/typecode/MemberedTypeCode.java
>          if (member.isAnnotationOptional() && Kind.KIND_STRUCT != getKind())
Done in d0f6d82

2024-04-08 05:15 UTC, richiware commented on src/main/java/com/eprosima/idl/parser/typecode/MemberAppliedAnnotations.java
> +    public boolean isAnnotationOptional()
Done in d0f6d82

2024-04-08 05:15 UTC, richiware commented on src/main/java/com/eprosima/idl/parser/tree/Annotation.java
> +        if (getName().equals(Annotation.id_str) ||
Done in d0f6d82

2024-04-08 05:15 UTC, richiware commented on src/main/java/com/eprosima/idl/parser/tree/Annotation.java
> +    public static final String autoid_hash_value_str = "1";
Done in d0f6d82

2024-04-08 05:15 UTC, richiware commented on src/main/java/com/eprosima/idl/context/Context.java
> +        // Builtin annotations (IDL 4.2 - 8.3 section & XTypes 1.3 - 7.3.1.2.1 section)
Done in d0f6d82

2024-04-08 05:15 UTC, richiware commented on src/main/java/com/eprosima/idl/context/Context.java
> +import com.eprosima.idl.parser.typecode.Bitmask;
Done in d0f6d82

2024-04-08 08:19 UTC, JLBuenoLopez-eProsima reviewed
LGTM though I have left a small nitpick. Nevertheless, if the CI is green, this could be merge.

2024-04-08 08:19 UTC, JLBuenoLopez-eProsima commented on src/main/java/com/eprosima/idl/parser/typecode/MemberedTypeCode.java
> +                    ": @bit_bound annotations only supported for enumeration's members or bitmask's members.");
Nitpick: Now that every builtin annotation has its name defined in a variable, maybe we can use it in these methods. Some of them are using the variables and some others not.

2024-04-08 10:50 UTC, JLBuenoLopez-eProsima reviewed
LGTM

2024-04-08 11:58 UTC, richiware approved these changes
Tested in [this CI job](https://github.com/eProsima/Fast-DDS-Gen/actions/runs/8598722742/job/23560164577?pr=327)

2024-04-08 11:58 UTC, merged