[20755] Improve path processing
eProsima/IDL-Parser pull request #131
Opened 2024-04-16 07:50 UTC by elianalf

This PR introduces improvements regarding path processing:
* Path normalization
* Replace '\' with '/' in dependencies

2024-04-25 10:05 UTC, Mario-DL requested changes

2024-04-25 10:05 UTC, Mario-DL commented on src/main/java/com/eprosima/idl/context/Context.java
> +                                    dependency_to_add = dependency_to_add.replace('\\', '/');
I think that the suggested change on the issue was on a previous line
```suggestion
                                    includeFile.substring(0, includeFile.length() - 4).replace('.', '_').replace('\\', '/'));
                                    // Change back to "." for relative paths.
                                    dependency_to_add = dependency_to_add.replaceAll("__/", "../");
```

2024-04-25 10:07 UTC, Mario-DL commented on src/main/java/com/eprosima/idl/context/Context.java
> +                                    dependency_to_add = dependency_to_add.replace('\\', '/');
Well, I think its the same in this case, as in this recent version, a temporal object is created. Resolving

2024-04-25 10:08 UTC, Mario-DL approved these changes
LGTM, we may need to backport this

2024-04-26 05:39 UTC, merged

2024-04-26 05:40 UTC, EduPonz commented
@elianalf can you please study the need of backports

2024-04-29 06:00 UTC, elianalf commented
@Mergifyio backport 2.0.x 3.0.x 4.0.x-devel