Annotations for union's discriminators
eProsima/IDL-Parser pull request #148
Opened 2024-06-24 08:00 UTC by richiware

## Description

This PR adds annotations for union's discriminator in the grammar. Also it adds the `@default` annotation for union's discriminator in the library. And it changes how to calculate the discriminator's value for default case in primitive types: instead of searching for the lower value, it searches the greater one.

## Contributor Checklist

- [x] Commit messages follow the project guidelines. 
- [x] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally
- [ ] Any new/modified methods have been properly documented.
- [x] Changes are backport compatible: they do **NOT** break ABI nor change library core behavior. 
- [x] Changes are API compatible. 
- *N/A* Applicable backports have been included in the description.

## Reviewer Checklist

- [ ] The PR has a milestone assigned.
- [ ] The title and description correctly express the PR's purpose.
- [ ] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

2024-07-01 13:19 UTC, MiguelCompany requested changes

2024-07-01 13:19 UTC, MiguelCompany commented on src/main/java/com/eprosima/idl/generator/manager/TemplateUtil.java
> +                // the maximum value of the primitive type for the default implicit value.
```suggestion
                // For primitive types, if the default case was not defined, use the highest unused value as the implicit default value.
```

2024-07-01 13:19 UTC, MiguelCompany commented on src/main/java/com/eprosima/idl/generator/manager/TemplateUtil.java
> +                        dvalue = Long.MAX_VALUE;
I think we should start on different values for signed / unsigned types

2024-07-01 13:19 UTC, MiguelCompany commented on src/main/java/com/eprosima/idl/generator/manager/TemplateUtil.java
> +                            // Possible default implicit value used. Changing to test the former value.
```suggestion
                            // Possible default implicit value used. Try with the next lower value.
```

2024-07-01 13:19 UTC, MiguelCompany commented on src/main/java/com/eprosima/idl/parser/typecode/UnionTypeCode.java
> +        // the @default annotation value and if they matches store the union's member index.
```suggestion
        // Checks the discriminator has the @default annotation. In that case, check the union's member has a label with
        // the @default annotation value and if they match store the union's member index.
```

2024-07-01 13:19 UTC, MiguelCompany commented on src/main/java/com/eprosima/idl/parser/typecode/UnionTypeCode.java
> +                            return -2;
```suggestion
                            // Default value matches with more than one member.
                            return -2;
```

2024-07-01 13:19 UTC, MiguelCompany commented on src/main/java/com/eprosima/idl/parser/typecode/UnionTypeCode.java
> +            throw new RuntimeGenerationException("UnionTypeCode::getDefaultAnnotatedMember(): Discriminator has a default value but that value not found in label cases");
```suggestion
            throw new RuntimeGenerationException("UnionTypeCode::getDefaultAnnotatedMember(): Discriminator has a default value but that value was not found in label cases");
```

2024-07-05 08:58 UTC, richiware commented on src/main/java/com/eprosima/idl/generator/manager/TemplateUtil.java
> +                        dvalue = Long.MAX_VALUE;
there is no `unsigned` types in Java and I tried to avoid put a liternal number.

2024-07-05 09:02 UTC, richiware commented on src/main/java/com/eprosima/idl/generator/manager/TemplateUtil.java
>                  while(found);
You mean we have to select  in this case as default value a user's label case like, for example, the label value 0?

2024-07-05 09:04 UTC, richiware commented on src/main/java/com/eprosima/idl/parser/typecode/UnionTypeCode.java
> +            throw new RuntimeGenerationException("UnionTypeCode::getDefaultAnnotatedMember(): Discriminator has a default value but that value not found in label cases");
Done in 2a1cc06

2024-07-05 09:04 UTC, richiware commented on src/main/java/com/eprosima/idl/parser/typecode/UnionTypeCode.java
> +                            return -2;
Done in 2a1cc06

2024-07-05 09:05 UTC, richiware commented on src/main/java/com/eprosima/idl/parser/typecode/UnionTypeCode.java
> +        // the @default annotation value and if they matches store the union's member index.
Done in 2a1cc06

2024-07-05 09:05 UTC, richiware commented on src/main/java/com/eprosima/idl/generator/manager/TemplateUtil.java
> +                            // Possible default implicit value used. Changing to test the former value.
Done in 2a1cc06

2024-07-05 09:05 UTC, richiware commented on src/main/java/com/eprosima/idl/generator/manager/TemplateUtil.java
> +                // the maximum value of the primitive type for the default implicit value.
Done in 2a1cc06

2024-07-05 09:10 UTC, MiguelCompany commented on src/main/java/com/eprosima/idl/generator/manager/TemplateUtil.java
>                  while(found);
Yes

2024-07-05 10:01 UTC, richiware commented on src/main/java/com/eprosima/idl/generator/manager/TemplateUtil.java
>                  while(found);
Done in b775689

2024-07-05 10:15 UTC, MiguelCompany approved these changes

2024-07-06 21:11 UTC, richiware commented
Tested in [this action](https://github.com/eProsima/Fast-DDS-Gen/actions/runs/9807109492/job/27080187605?pr=361)

2024-07-08 06:21 UTC, merged