Support for generating recursive structures
eProsima/IDL-Parser pull request #57
Opened 2022-08-03 06:09 UTC by richiware

According to OMG IDL standard, recursive structures are supported using `sequences` and forward declarations. This PR
add support for this and also:

- Improve test execution
- Fix bug generating bitset and bitmask

2023-01-03 08:44 UTC, MiguelCompany commented
@richiware Would you mind resolving the conflicts here?

2023-02-08 12:22 UTC, jsantiago-eProsima requested changes

2023-02-08 12:22 UTC, jsantiago-eProsima commented on src/main/java/com/eprosima/idl/parser/typecode/SequenceTypeCode.java
> +            return "100";
Why 100 and not 255 as stated in getMaxSerializedSize templates?

2023-02-15 07:10 UTC, richiware commented on src/main/java/com/eprosima/idl/parser/typecode/SequenceTypeCode.java
> +            return "100";
The value was always 100 for unbounded sequences. For example you can see this here:

https://github.com/eProsima/Fast-DDS-Gen/blob/master/src/main/java/com/eprosima/fastcdr/idl/templates/FastCdrCommon.stg#L360

2023-02-15 07:22 UTC, richiware commented on src/main/java/com/eprosima/idl/context/Context.java
> +import com.eprosima.idl.parser.typecode.EnumTypeCode;
Done in 6f5e622

2023-02-15 07:22 UTC, richiware commented on src/main/java/com/eprosima/idl/context/Context.java
> +import com.eprosima.idl.parser.typecode.UnionTypeCode;
Done in 6f5e622

2023-02-16 13:36 UTC, jsantiago-eProsima approved these changes

2023-02-16 14:00 UTC, merged