[17352] Added post-creation filter for out of bounds positions
eProsima/IDL-Parser pull request #63
Opened 2023-02-23 13:49 UTC by jsantiago-eProsima

Currently, the `@bit_bound` seems to be applied after the `@position` calculation for members of a bitmask. This PR introduces a filter that removes all out-of-bounds members after the bit_bound update.

2023-02-23 14:04 UTC, richiware requested changes

2023-02-23 14:04 UTC, richiware commented on src/main/java/com/eprosima/idl/parser/typecode/BitmaskTypeCode.java
> +                    m_value_bitmasks.remove(m_bitmasks.get(key).getPosition());
I think it is preferable the generation fails warning the user he has a mistake in its IDL file. Better than remove the bitvalue it will be to launch an exception to be caught by the parser.

2023-02-23 14:04 UTC, jsantiago-eProsima commented on src/main/java/com/eprosima/idl/parser/typecode/BitmaskTypeCode.java
> +                    m_value_bitmasks.remove(m_bitmasks.get(key).getPosition());
Removal of the bitvalue is the current behavior. I opted for not modifying it.

2023-02-27 15:15 UTC, richiware approved these changes

2023-02-28 06:34 UTC, merged