Support @optional and @extensibility annotations
eProsima/IDL-Parser pull request #80
Opened 2023-07-27 12:40 UTC by richiware

2023-08-23 12:30 UTC, JLBuenoLopez-eProsima requested changes

2023-08-23 12:30 UTC, JLBuenoLopez-eProsima commented on src/main/java/com/eprosima/idl/generator/manager/TemplateManager.java
> +    private STGroup strackgr_ = null;
I suggest removing this variable. It is used in some code that it has been commented out and in some methods that does not seem to be in use (I suggest removing these methods too):

* `addGroup(String, List<TemplateExtension>)`
* `createStringTemplate`

2023-08-23 12:30 UTC, JLBuenoLopez-eProsima commented on src/main/java/com/eprosima/idl/generator/manager/TemplateManager.java
>      }
This method does not seem to be to in use. Please, remove with the other legacy code.

2023-08-25 12:09 UTC, richiware commented on src/main/java/com/eprosima/idl/generator/manager/TemplateManager.java
> +        /*
Done in 3b643a6

2023-08-25 12:09 UTC, richiware commented on src/main/java/com/eprosima/idl/generator/manager/TemplateManager.java
> +    private STGroup strackgr_ = null;
Done in 3b643a6

2023-08-25 12:09 UTC, richiware commented on src/main/java/com/eprosima/idl/generator/manager/TemplateGroup.java
> +    */
Done in 3b643a6

2023-08-25 12:09 UTC, richiware commented on src/main/java/com/eprosima/idl/parser/typecode/UnionTypeCode.java
> +                default_member = new AbstractMap.SimpleEntry<>(++position, m);
Done in 3b643a6

2023-08-25 12:09 UTC, richiware commented on test/idls/optional.idl
> +};
Done in 3b643a6

2023-09-05 09:48 UTC, JLBuenoLopez-eProsima reviewed
Most comments are related to features that were tested in the previous test suite but that now are not tested after removing the IDLs from this repository.

I am also not sure if the extensibility annotation check is implemented correctly. XTypes v1.3 Table 21 specifies that these annotations apply to every Type Declaration. On the other hand, Table 12 specifies the impact of the annotation for the different types. The annotation only affects aggregated types, enumerated types and alias types. I think this implementation has only taken into account the aggregated types.

2023-09-05 09:48 UTC, JLBuenoLopez-eProsima commented on test/idls/coverage_complex.idl
> -    @Key octet my_key;
This annotation is not being currently tested (after removing these IDL files).

2023-09-05 09:48 UTC, JLBuenoLopez-eProsima commented on test/idls/forward_decls.idl
> -};
Annotation definition is not being tested either (and the [documentation](https://fast-dds.docs.eprosima.com/en/latest/fastddsgen/dataTypes/dataTypes.html#annotations) includes this feature as supported)

2023-09-05 09:48 UTC, JLBuenoLopez-eProsima commented on test/idls/forward_decls.idl
> -        @min(5) long mylong_two;
Impressive! Testing that the annotation @min is parsed, even if it is not really implemented into the generated code :laughing:

2023-09-05 09:48 UTC, JLBuenoLopez-eProsima commented on test/idls/forward_decls.idl
> -    @MyAnnotation(my_value=55,name="AnnotationName")
Annotation application was also tested, though this is not generated into the code per se, so with the current test suite I am not sure if there is an easy way to check it.

2023-09-05 09:48 UTC, JLBuenoLopez-eProsima commented on test/idls/forward_decls.idl
> -    @bit_bound(8)
Another untested annotation

2023-09-05 09:48 UTC, JLBuenoLopez-eProsima commented on test/idls/new_features_4_2.idl
> -    uint64 uint64_;
This new types are not being tested with the new IDLs.

2023-09-05 09:48 UTC, JLBuenoLopez-eProsima commented on test/idls/include.idl
> -const octet CONST_DEFINITION_VALUE_1 = 1;
I am not sure if this regression test has been kept in the new test suite.

2023-09-05 10:02 UTC, JLBuenoLopez-eProsima approved these changes
After reviewing the XTypes v1.3 specification again, clause 7.3.1.2.1.8 states:

> This annotation may be applied to the definitions of aggregated types. It shall be considered an error for it to be applied to the same type multiple times.

So current implementation that only checks aggregated types for multiple annotation definition seems to be correct.

The other comments have to be implemented in the new [DDS Types Test](https://github.com/eProsima/dds-types-test) repository, so I am approving this PR

2023-09-05 10:04 UTC, merged