Extra functionality for support external members [19710]
eProsima/IDL-Parser pull request #97
Opened 2023-10-13 09:40 UTC by richiware

Depends on:
- eprosima/fast-cdr#170

2023-10-17 13:36 UTC, JLBuenoLopez-eProsima requested changes

2023-10-17 13:36 UTC, JLBuenoLopez-eProsima commented on src/main/java/com/eprosima/idl/parser/typecode/MemberedTypeCode.java
> +                    ": @bit_bound annotations only supported for structure's members or union's members.");
```suggestion
                    ": @bit_bound annotations only supported for enumeration's members or bitmask's members.");
```

2023-10-17 13:36 UTC, JLBuenoLopez-eProsima commented on src/main/java/com/eprosima/idl/parser/typecode/MemberedTypeCode.java
> +    public boolean addMember(Member member) throws ParseException
I am missing the following check: 

> XTypes v1.3 Clause 7.3.1.2.1.2 & 7.3.1.2.1.3 It is an error to declare the same member as both optional and as a key.

2023-10-24 12:28 UTC, richiware commented on src/main/java/com/eprosima/idl/parser/typecode/MemberedTypeCode.java
> +    public boolean addMember(Member member) throws ParseException
Done in 94abe2c

2023-10-24 12:28 UTC, richiware commented on src/main/java/com/eprosima/idl/parser/typecode/MemberedTypeCode.java
> +                    ": @bit_bound annotations only supported for structure's members or union's members.");
Done in 94abe2c

2023-10-24 12:30 UTC, JLBuenoLopez-eProsima approved these changes
LGTM

2023-10-24 12:30 UTC, merged